# My First Workflow
name: My First Workflow

on: [push, pull_request]

jobs:
  job1:
   name: My first job
   runs-on: ubuntu-latest
   steps :
    - uses: actions/setup-node@v2

    - name: Install Dependencies
      run: npm install

    - name: Clean install dependencies and build
      run:
        npm ci
        npm run build
      working-directory: ./temp
      shell: bash
