# My First Workflow
name: My First Workflow

on: [push, pull_request]

jobs:
  job1:
   name: My first job
   runs-on: ubuntu-latest
   steps :
    - uses: actions/checkout@v3

    - name: Install python
      uses: actions.setup-python@v4
      with:
        python-version: '3.10'

    - name : call youtube api
      run: python main.py
      env:
        YOUTUBE: ${{ secrets.API_KEY }}
